name: jupyter0.02

on:
  workflow_dispatch:

jobs:
  run-jupyter:
    runs-on: ubuntu-latest

    steps:
      - name: Run container
        run: |
          docker run -d -p 10000:8888 quay.io/jupyter/scipy-notebook:2025-03-14
          
      - name: Show running containers
        run: docker ps
        
      - name: Run f1r3Flared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared
          ./cloudflared --version
          ./cloudflared tunnel --url http://localhost:1000

      - name: Keep alive for 5 hours
        run: sleep 18000
