name: m4k 0.0.3

on:
  workflow_dispatch:

jobs:
  run-macos-vm:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 hours

    env:
      DISPLAY: "${{ env.DISPLAY || ':0.0' }}"
      SHORTNAME: catalina
      VM_PORT: 50922
      TUNNEL_URL: "http://localhost:50922"

    steps:
      - name: Start macOS VM container
        run: |
          docker run -d \
            --device=/dev/kvm \
            -p $VM_PORT:10022 \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            -e "DISPLAY=$DISPLAY" \
            -e "SHORTNAME=$SHORTNAME" \
            sickcodes/docker-osx:v8.5.2  # Specify a stable tag

      - name: List running containers
        run: docker ps

      - name: Download cloudflared binary
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared

      - name: Verify cloudflared version
        run: ./cloudflared --version

      - name: Start Cloudflare Tunnel
        run: ./cloudflared tunnel --url $TUNNEL_URL

      # Optionally clean up containers and binaries after completion
      - name: Cleanup
        run: |
          docker rm -f $(docker ps -aq --filter ancestor=sickcodes/docker-osx:v8.5.2) || true
          rm -f cloudflared
