name: m4k 0.0.1

on:
  workflow_dispatch:

jobs:
  run-jupyter:
    runs-on: ubuntu-latest

    steps:
      - name: Run container
        run: |
          docker run -d -p \
          --device=/dev/kvm \
          -p 50922:10022 \
          -v /tmp/.X11-unix:/tmp/.X11-unix \
          -e "DISPLAY=${DISPLAY:-:0.0}" \
          -e SHORTNAME=catalina \
          sickcodes/docker-osx:latest

# docker build -t docker-osx .
          
      - name: Show running containers
        run: docker ps
        
      - name: Run f1r3Flared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared
          ./cloudflared --version
          ./cloudflared tunnel --url http://localhost:50922

      - name: Keep alive for 5 hours
        run: sleep 18000
