name: m4k 0.0.4

on:
  workflow_dispatch:

jobs:
  run-macos-vm:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 hours

    env:
      DISPLAY: ${{ env.DISPLAY }}
      SHORTNAME: catalina
      VM_PORT: 50922
      TUNNEL_URL: "http://localhost:50922"

    steps:
      - name: Start macOS VM container
        run: |
          docker run -d \
            --device=/dev/kvm \
            -p $VM_PORT:10022 \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            -e "DISPLAY=$DISPLAY" \
            -e "SHORTNAME=$SHORTNAME" \
            sickcodes/docker-osx:v8.5.2  # Specify a stable tag

      - name: List running containers
        run: docker ps

      - name: Download cloudflared binary
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          mv cloudflared-linux-amd64 cloudflared

      - name: Verify cloudflared version
        run: ./cloudflared --version

      - name: Start Cloudflare Tunnel
        run: ./cloudflared tunnel --url $TUNNEL_URL

