name: Chromium Flared0.4

on:
  workflow_dispatch:

jobs:
  run-chromium:
    runs-on: ubuntu-latest

    steps:
      - name: Run Chromium container
        run: |
          docker run -d \
            --name=chromium \
            --security-opt seccomp=unconfined \
            -e PUID=1000 \
            -e PGID=1000 \
            -e TZ=Etc/UTC \
            -e CHROME_CLI=https://www.linuxserver.io/ \
            -p 3000:3000 \
            -p 3001:3001 \
            -v /path/to/chromium/config:/config \
            --shm-size="1gb" \
            --restart unless-stopped \
            lscr.io/linuxserver/chromium:latest

      - name: Check if Chromium is reachable
        run: curl -v http://localhost:3001 || exit 1

      - name: Show running containers
        run: docker ps
        
      - name: Run Flared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
          cloudflared --version
          cloudflared tunnel --url http://localhost:3001

      - name: Keep alive for 5 hours
        run: sleep 18000
          
